### ISSUE TITLE
Does not work in OSX terminal, only iterm

### ISSUE THREAD

**Issue by theicfire** [kapetan/osx-mouse#12] opened 2019-11-27 22:47 UTC
# Steps to reproduce
```
// Call this index.js
var mouse = require('osx-mouse')();
console.log('hello');
mouse.on('move', function(x, y) {
	console.log(x, y);
});
```

Do the following in Mac terminal (not iterm):
- `npm install osx-mouse`
- `node index.js`
- Move the mouse around

# Issue
In iterm, this prints "hello", and then prints more when the mouse is moved.
In Mac terminal, it just prints "hello". I expect it would function the same as iterm.

System details:
- Node v11.11.0
- Mac 10.14.6

# Why does this matter?
I'm building a packaged electron application that includes osx-mouse, and it's not working. I believe the issue is the same, because the packaged app works when running from iterm, but not from finder or the Mac terminal.

My best guess is there's some sort of permission issue, and iterm has that permission whereas Mac terminal does not.

**Comment by theicfire** [comment] 2019-11-27 22:52
Fundamentally, the problem here is that `OnMouseEvent` is not being called. Both `CFMachPortRef tap` and `CFRunLoopSourceRef source` are not null. There's some weird Mac thing going on here..

**Comment by theicfire** [comment] 2019-11-27 22:55
When I remove Iterm from "accessibility" it stops working. Here's a screenshot: https://www.dropbox.com/s/cgr4swwyeay6gc0/Screenshot%202019-11-27%2014.54.47.png?dl=0

So I guess terminal just doesn't have "accessibility" access?

**Comment by theicfire** [comment] 2019-11-27 22:58
It is! I added terminal to the accessibility apps (with the + button) and now it works. Woo!

**Comment by kapetan** [comment] 2020-09-09 13:32
This seems to be a duplicate of https://github.com/kapetan/osx-mouse/issues/8

**Closed by kapetan** 2020-09-09 13:32 UTC
