### ISSUE TITLE
No events printed on Mojave

### ISSUE THREAD

**Issue by theicfire** [kapetan/osx-mouse#14] opened 2019-12-04 00:48 UTC
Running the examples in OSX Mojave doesn't print any output. Maybe it's possible that there are some additional permissions that are required, as mentioned here: https://www.felix-schwarz.org/blog/2018/08/new-apple-event-apis-in-macos-mojave

**Comment by kapetan** [comment] 2020-09-09 13:31
This is a duplicate of https://github.com/kapetan/osx-mouse/issues/8

**Closed by kapetan** 2020-09-09 13:31 UTC
